services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: {{project-name}}
      POSTGRES_PASSWORD: {{project-name}}
      POSTGRES_DB: {{project-name}}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
